/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.layerd.view;

import edu.ijse.layerd.controller.FaclttyDetailsController;
import edu.ijse.layerd.dto.FacultyDetailsDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ravindusaranga
 */
public class FacultyDetailsView extends javax.swing.JFrame {
private FaclttyDetailsController facultyDetailsController = new FaclttyDetailsController();
    /**
     * Creates new form FacultyDetailsView
     */
    public FacultyDetailsView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblFacultyID = new javax.swing.JLabel();
        txtFacultyID = new javax.swing.JTextField();
        lblFacultyID1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblFacultyID2 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Faculty Management System - Faculty Details");

        lblFacultyID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFacultyID.setText("FacultyID");

        lblFacultyID1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFacultyID1.setText("Name");

        lblFacultyID2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFacultyID2.setText("Department");

        lblContact.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblContact.setText("Contact");

        tblFaculty.setFont(new java.awt.Font("Impact", 1, 14)); // NOI18N
        tblFaculty.setForeground(new java.awt.Color(204, 204, 204));
        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacultyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFaculty);

        btnAdd.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(102, 102, 102));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(102, 102, 102));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        btnBack2.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(102, 102, 102));
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        btnUpdate1.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(102, 102, 102));
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFacultyID2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFacultyID1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContact, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(330, 330, 330))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFacultyID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyID1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFacultyID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        dispose();
        new AdminDashboard().setVisible(true);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        add();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        update();
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        delete();
    }//GEN-LAST:event_DeleteActionPerformed

    private void tblFacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacultyMouseClicked
        search();
    }//GEN-LAST:event_tblFacultyMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblFacultyID;
    private javax.swing.JLabel lblFacultyID1;
    private javax.swing.JLabel lblFacultyID2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tblFaculty;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtFacultyID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
private void add() {
            FacultyDetailsDto faculty = new FacultyDetailsDto(
                txtFacultyID.getText(),
                txtName.getText(),             
                txtDepartment.getText(),
                txtContact.getText()               
            );
            
            try{
            String resp = facultyDetailsController.add(faculty);
            JOptionPane.showMessageDialog(this,resp);
            loadTable();
            clear();
            }catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
            } 
}
    private void clear(){
        txtFacultyID.setText("");
        txtName.setText("");
        txtDepartment.setText("");
        txtContact.setText("");
    }
   /*public void loadTable(){
         try {
            String columns[] = {"FacultyID", "Name", "Department", "Contact"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tblFaculty.setModel(dtm);
            
            ArrayList<FacultyDetailsDto> FacultyDetailsDtos = facultyDetailsController.getAll();
            for (FacultyDetailsDto faculty : FacultyDetailsDtos) {
                Object[] rowData = {faculty.getFacultyID(),faculty.getName(),faculty.getDepartment(),faculty.getContact() };
                dtm.addRow(rowData);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }*/
    public void loadTable(){
    try {
        String columns[] = {"FacultyID", "Name", "Department", "Contact"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblFaculty.setModel(dtm);

        ArrayList<FacultyDetailsDto> FacultyDetailsDtos = facultyDetailsController.getAll();
        if (FacultyDetailsDtos == null) {
            System.out.println("No data received from controller");
            return;
        }

        for (FacultyDetailsDto faculty : FacultyDetailsDtos) {
            System.out.println("Adding faculty: " + faculty.getFacultyID()); // Debugging output
            Object[] rowData = {
                faculty.getFacultyID(),
                faculty.getName(),
                faculty.getDepartment(),
                faculty.getContact()
            };
            dtm.addRow(rowData);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    
    private void search(){
         String FacultyID = tblFaculty.getValueAt(tblFaculty.getSelectedRow(), 0).toString();
        try {
            FacultyDetailsDto faculty = facultyDetailsController.search(FacultyID);
            if(faculty != null){
                txtFacultyID.setText(faculty.getFacultyID());
                txtName.setText(faculty.getName());
                txtDepartment.setText(faculty.getDepartment());
                txtContact.setText(faculty.getContact());
                
            } else {
                JOptionPane.showMessageDialog(this, "Data not found");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void delete(){
      try {
            String resp = facultyDetailsController.delete(txtFacultyID.getText());
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clear();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }
    public void update(){
         FacultyDetailsDto facultyDto = new FacultyDetailsDto(
                txtFacultyID.getText(),
                txtName.getText(),
                txtDepartment.getText(),
                txtContact.getText()
        );
        
        try {
            String resp = facultyDetailsController.update(facultyDto);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clear();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
            
}
